apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/tools/*
    - ./infra/database/*
    - ./infra/nginx/*
      - ./infra/k8s/*
portForward:
  - resourceType: deployment
    resourceName: mongodb-event-depl
    port: 27017
    localPort: 8000
  - resourceType: deployment
    resourceName: mongodb-event-query-depl
    port: 27017
    localPort: 8001
  - resourceType: deployment
    resourceName: rabbitmq-depl
    port: 15672
    localPort: 15672
build:
  local:
    push: false
  artifacts:
  - image: vmquynh/auth
    context: backend/auth-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
   - image: vmquynh/user
    context: backend/user-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: . 
  - image: vmquynh/web-app
    context: frontend/web-app
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.js"
        dest: .