apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/tools/*
    - ./infra/database/*
    - ./infra/nginx/*
    - ./infra/k8s/*
    # - ./infra/hpa/*
portForward:
  - resourceType: deployment
    resourceName: mongodb-event-depl
    port: 27017
    localPort: 8000
  - resourceType: deployment
    resourceName: mongodb-event-query-depl
    port: 27017
    localPort: 8001
build:
  local:
    push: false
  artifacts:
  - image: vmquynh/auth
    context: backend/auth-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: vmquynh/user
    context: backend/user-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: vmquynh/game
    context: backend/game-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: vmquynh/web-app
    context: frontend/web-app
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.js"
        dest: .
  - image: nlhkha03/event-command
    context: backend/event-command-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: nlhkha03/event-query
    context: backend/event-query-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: nlhkha03/image
    context: backend/image-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: tvphuc/notification-service
    context: backend/notification-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
 
