apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host:
      http:
        paths:
          - path: /api/auth/
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port: 
                  number: 3000 
          - path: /api/user-management/
            pathType: Prefix
            backend:
              service:
                name: user-srv
                port: 
                  number: 3000
          - path : /api/events_query/
            pathType: Prefix
            backend:
              service:
                name: event-query-srv
                port: 
                  number: 3000
          - path: /api/events/
            pathType: Prefix
            backend:
              service:
                name: event-srv
                port: 
                  number: 3000
          - path: /api/vouchers/
            pathType: Prefix
            backend:
              service:
                name: event-srv
                port: 
                  number: 3000
          - path: /api/event_create_bff/
            pathType: Prefix
            backend:
              service:
                name: event-create-bff-srv
                port: 
                  number: 3000
          - path: /api/image/
            pathType: Prefix
            backend:
              service:
                name: image-srv
                port: 
                  number: 3000 
          - path: /api/game/
            pathType: Prefix
            backend:
              service:
                name: game-srv
                port: 
                  number: 3000 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app-srv
                port: 
                  number: 3000                                                    