CREATE OR REPLACE FUNCTION FUNC_FIND_ALL_CUSTOMER()
RETURNS TABLE (
	ID INTEGER,
    NAME VARCHAR,
    EMAIL VARCHAR,
    PHONENUM VARCHAR,
    PASSWORD VARCHAR,
    ROLE TEXT,
    STATUS BOOLEAN,
    GENDER VARCHAR,
    AVATAR_URL VARCHAR
)
LANGUAGE SQL
AS $$
    SELECT U.*, C.GENDER, C.AVATAR_URL
    FROM "USER" U JOIN "CUSTOMER" C
	ON U.ID = C.USERID;
$$;
