CREATE OR REPLACE PROCEDURE SP_CREATE_BRAND(
    P_USERID INTEGER,
	P_FIELD VARCHAR,
	P_ADDRESS VARCHAR
)
LANGUAGE SQL
AS $$
    INSERT INTO "BRAND" (USERID, FIELD, ADDRESS)
	VALUES (P_USERID, P_FIELD, P_ADDRESS);
$$;