CREATE OR REPLACE PROCEDURE SP_CREATE_CUS(
    P_USERID INTEGER,
	P_GENDER VARCHAR,
	P_AVATAR_URL VARCHAR,
	P_FACEBOOK_URL VARCHAR
)
LANGUAGE SQL
AS $$
    INSERT INTO "CUSTOMER" (USERID, GENDER, AVATAR_URL, FACEBOOK_URL)
	VALUES (P_USERID, P_GENDER, P_AVATAR_URL, P_FACEBOOK_URL);
$$;