apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: vmquynh/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: "jwt"
            - name: TWILIO_ACCOUNT_SID
              value: "AC1229af94be58e8f1292f265d9f1aab08"
            - name: TWILIO_AUTH_TOKEN
              value: "cf46bb62cdb8ea00d805829d3ac34c8c"
            - name: TWILIO_PHONE_NUMBER
              value: "+84284401157"
            - name: TWILIO_MESSAGING_SERVICE_SID
              value: "MG1182c151219c2a50fd9af49aab5e6ba7"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000