apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-query
  template:
    metadata:
      labels:
        app: event-query
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
        - name: wait-for-redis
          image: busybox:1.31
          command: ['sh', '-c', 'until nc -zv redis 6379; do echo "Waiting for Redis..."; sleep 5; done']
      containers:
        - name: event-query
          image: nlhkha03/event-query
---
apiVersion: v1
kind: Service
metadata:
  name: event-query-srv
spec:
  selector:
    app: event-query
  ports:
    - name: event-query
      protocol: TCP
      port: 3000
      targetPort: 3000

          