apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: vmquynh/game
          volumeMounts:
            - mountPath: "/app/data"
              name: game-storage
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DB_HOST
              value: "postgres-game-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "game-db"
            - name: DB_ADMIN
              value: "game-admin"
            - name: DB_PASSWORD
              value: "game-admin"
      volumes:
        - name: game-storage
          persistentVolumeClaim:
            claimName: blob-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: game-srv
spec:
  selector:
    app: game
  ports:
    - name: game
      protocol: TCP
      port: 3000
      targetPort: 3000