apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-user-srv 5432; do echo waiting for postgres; sleep 2; done;']
        
      containers:
        - name: user
          image: vmquynh/user
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: "jwt"
            - name: DB_HOST
              value: "postgres-user-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "user-db"
            - name: DB_ADMIN
              value: "user-admin"
            - name: DB_PASSWORD
              value: "user-admin"
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000