CREATE OR REPLACE FUNCTION FUNC_FIND_CUSTOMER_BY_ID(P_USERID INTEGER)
RETURNS TABLE (
	ID INTEGER,
    NAME VARCHAR,
    EMAIL VARCHAR,
    PHONENUM VARCHAR,
    PASSWORD VARCHAR,
    ROLE TEXT,
    STATUS BOOLEAN,
    GENDER VARCHAR,
    AVATAR_URL VARCHAR
)
LANGUAGE SQL
AS $$
    SELECT U.*, C.GENDER, C.AVATAR_URL
    FROM "USER" U JOIN "CUSTOMER" C 
	ON U.ID = C.USERID
	WHERE U.ID = P_USERID;
$$;
