CREATE OR REPLACE FUNCTION FUNC_FIND_BRAND_BY_EMAIL(P_EMAIL VARCHAR)
RETURNS TABLE (
	ID INTEGER,
    NAME VARCHAR,
    EMAIL VARCHAR,
    PHONENUM VARCHAR,
    PASSWORD VARCHAR,
    ROLE TEXT,
    STATUS BOOLEAN,
    FIELD VARCHAR,
    ADDRESS VARCHAR,
    AVATAR_URL VARCHAR
)
LANGUAGE SQL
AS $$
    SELECT U.*, B.FIELD, B.ADDRESS, B.AVATAR_URL
    FROM "USER" U JOIN "BRAND" B 
	ON U.ID = B.USERID
	WHERE U.EMAIL = P_EMAIL;
$$;
