CREATE TABLE "USER" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONENUM VARCHAR(10),
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20),
    STATUS BOOLEAN
);

CREATE TABLE "BRAND" (
    USERID INT NOT NULL PRIMARY KEY,
    FIELD VARCHAR(255),
    AVATAR_URL VARCHAR(255),
    ADDRESS VARCHAR(255),
    LAT DECIMAL(9, 6),
    LONG DECIMAL(9, 6),
    FOREIGN KEY (USERID) REFERENCES "USER"(ID)
);

CREATE TABLE "CUSTOMER" (
    USERID INT NOT NULL PRIMARY KEY,
    GENDER VARCHAR(10),
    AVATAR_URL VARCHAR(255),
    FACEBOOK_URL VARCHAR(255),
    FOREIGN KEY (USERID) REFERENCES "USER"(ID)
);