CREATE OR REPLACE PROCEDURE SP_CREATE_USER(
	P_NAME VARCHAR,
	P_EMAIL VARCHAR,
	P_PHONENUM VARCHAR,
	P_PASSWORD VARCHAR,
	P_ROLE VARCHAR,
	P_STATUS BOOLEAN
)
LANGUAGE SQL 
AS $$
	INSERT INTO "USER" (NAME, EMAIL, PHONENUM, PASSWORD, ROLE, STATUS) 
    VALUES (P_NAME, P_EMAIL, P_PHONENUM, P_PASSWORD, P_ROLE, P_STATUS);
$$;