CREATE OR REPLACE PROCEDURE SP_CREATE_BRAND(
    P_USERID INTEGER,
	P_FIELD VARCHAR,
	P_ADDRESS VARCHAR,
	P_LAT NUMERIC,
	P_LONG NUMERIC
)
LANGUAGE SQL
AS $$
    INSERT INTO "BRAND" (USERID, FIELD, ADDRESS, LAT, LONG)
	VALUES (P_USERID, P_FIELD, P_ADDRESS, P_LAT, P_LONG);
$$;

