apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-game-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /mnt/data/postgres-game
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-game-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi